# Generated by Django 6.0.3 on 2026-05-10 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_available_from_event_available_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="available_from",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="event",
            name="available_until",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
