# Generated by Django 6.0.3 on 2026-03-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_activitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                ],
                default="success",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create_teacher", "Create Teacher"),
                    ("edit_teacher", "Edit Teacher"),
                    ("delete_teacher", "Delete Teacher"),
                    ("create_event", "Create Event"),
                    ("edit_event", "Edit Event"),
                    ("delete_event", "Delete Event"),
                    ("upload_excel", "Upload Excel"),
                    ("send_activation_link", "Send Activation Link"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("error", "Error"),
                ],
                max_length=50,
            ),
        ),
    ]
